INSERT INTO REGIAO VALUES(NULL, 'Norte', 44);
INSERT INTO REGIAO VALUES(NULL, 'Nordeste', 13832);
INSERT INTO REGIAO VALUES(NULL, 'Sudeste', 89657);
INSERT INTO REGIAO VALUES(NULL, 'Sul', 122);
INSERT INTO REGIAO VALUES(NULL, 'Centro-Oeste', 2581);